### ISSUE TITLE
[7/3/2020, 19:04:40] Error: The requested platform 'MyQ2' was not registered by any plugin.

### ISSUE THREAD

**Issue by DNSGeek** [hjdhjd/homebridge-myq2#50]
After the v2 update, I just keep getting this in my logs, and homebridge will not start.
```
[7/3/2020, 19:04:40] Error loading platform requested in your config.json at position 5
[7/3/2020, 19:04:40] Error: The requested platform 'MyQ2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by donavanbecker** [comment]
You have to change your config to myQ from MyQ2

**Comment by DNSGeek** [comment]
It already is MyQ2
            "platform": "MyQ2"

**Comment by DNSGeek** [comment]
Ok, that worked. Maybe have the error message state that so people don't have to bug you?

Thanks for the update!
