### ISSUE TITLE
Updating from 2.0.11 to 2.0.14 = The requested platform 'myQ' was not registered by any plugin.

### ISSUE THREAD

**Issue by 4rsfed** [hjdhjd/homebridge-myq2#93]
Upgrading from 2.0.11 to 2.0.14 gives the following error:

`Error: The requested platform 'myQ' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11`

Rolling back to 2.0.11 resolves the problem 

I don't see anything in the [changelog](https://github.com/hjdhjd/homebridge-myq2/blob/master/CHANGELOG.md) mentioning any changes that need to take place on the config.json?

**Comment by hjdhjd** [comment]
Please uninstall and reinstall the plugin and see if that solves this one. There's nothing that's shifted that should cause this...but clearly something is. :smile: Please let me know if uninstalling and reinstalling works. Thanks!

**Comment by 4rsfed** [comment]
@hjdhjd uninstall and install of 2.1.4 did work 🤷‍♂️ 
Thank you!
