### ISSUE TITLE
2.1.4 and no alerts

### ISSUE THREAD

**Issue by DNSGeek** [hjdhjd/homebridge-myq2#95]
Since updating to the 2.1.4 release yesterday, I no longer receive alerts when my garage door is opened or closed.

**Comment by hjdhjd** [comment]
Without more context and detail, this is impossible to troubleshoot or address. Please provide additional details of your setup, any relevant logging, and how to recreate the problem in question.

**Comment by suedehed** [comment]
Updated to 2.1.4 this morning and here is what I am seeing:

[7/22/2020, 12:39:28] [Garage Door] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/dd90ffe2-4637-4119-b888-416426c7caf8/Devices failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

**Comment by hjdhjd** [comment]
@suedehed This is not an issue and can be safely ignored. Please see https://github.com/hjdhjd/homebridge-myq2/issues/94#issuecomment-662202103 for details.
