### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by Infallibleman** [hjdhjd/homebridge-myq2#97]
[7/29/2020, 11:01:04 AM] [myQ] double garage: Closed.
[7/29/2020, 11:01:04 AM] [myQ] Single Garage: Closed.
[7/29/2020, 11:03:06 AM] [myQ] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/a6a214ac-4d4a-4a7c-accc-cd8fc941e7cd/Devices failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
[7/29/2020, 11:03:06 AM] [myQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.

**Comment by joconor** [comment]
Having an almost identical problem. Same stack trace, but the only difference is the error is EAI_AGAIN. Perhaps difference is underlying IP stack. I'm running on Raspberry PI 3B+ Raspbian GNU/Linux 10 (buster) with Node.js version v12.18.3

**Comment by hjdhjd** [comment]
This is not a bug. Please read the README. [There is a section specifically on this topic](https://github.com/hjdhjd/homebridge-myq2#myq-errors)
