### ISSUE TITLE
After update to 2.1.9, seeing only "Internal Server Error" messages

### ISSUE THREAD

**Issue by jlg89** [hjdhjd/homebridge-myq2#99]
Updated the plugin to 2.1.9, and now I get this every couple of minutes in the log. Tried rebooting, no change:

8/14/2020, 11:25:40 AM [MyQ2] myQ API: Error: 500 Internal Server Error
8/14/2020, 11:25:40 AM [MyQ2] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.

**Comment by dppeak** [comment]
I'm seeing the same thing.

**Comment by hjdhjd** [comment]
As am I. Here's my question: does downgrading to 2.1.8 resolve this? You can test this by doing:

`npm -g install homebridge-myq2@2.1.8`

**Comment by hjdhjd** [comment]
I'm trying to resolve whether this is a plugin issue or a myQ issue. :smile:

**Comment by dppeak** [comment]
just started getting this with 2.1.9

[8/14/2020, 12:49:50 PM] [myQ] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/{_UUID deleted for security_}/Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

**Comment by hjdhjd** [comment]
@dppeak See above. Try the prior version and see if the issues persist. The error above is a network error. It's not obvious at the moment if the error is due to something in the plugin or the myQ servers.

**Comment by dppeak** [comment]
still see the "Error: 500 Internal Server Error" on 2.1.8

**Comment by dppeak** [comment]
actually, had to specifically uninstall 2.1.9 after installing 2.1.8 as it was still present.

**Comment by hjdhjd** [comment]
Which leads me to believe it's more on myQ's end than ours...I'm seeing these errors as well.

**Comment by hjdhjd** [comment]
I've seen the errors disappear in 2.1.8...so if others can confirm it works for them, I'll go and figure out the regression here.

For those reading this now:

Try:

```
npm -g uninstall homebridge-myq2
npm -g install homebridge-myq2@2.1.8
```

See if that eliminates the errors you're seeing.

**Comment by dppeak** [comment]
I ran the uninstall and installs you posted and will let you know if I see further errors.

**Comment by hjdhjd** [comment]
I've identified the issue and will be fixing it in an update shortly. Thanks.

**Comment by jlg89** [comment]
Not sure if this helps, but I uninstalled the plugin completely, reinstalled 2.1.9 and reconfigured, and I haven't seen any errors.

**Comment by dppeak** [comment]
Seeing this on 2.1.8

`[8/14/2020, 2:54:27 PM] [myQ] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/d528cad3-a1a5-4f0a-8bf9-8c3849c296a9/Devices failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
[8/14/2020, 2:54:27 PM] [myQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
`

**Comment by jlg89** [comment]
I saw that too, when I downgraded to 2.1.8. What happens if you uninstall the plugin completely, then reinstall 2.1.9 and only enter the myQ username/password (leave all other config settings at default)?

**Comment by dppeak** [comment]
i did the uninstall then installed 2.1.8

**Comment by hjdhjd** [comment]
Please update to v2.1.10 - just published. Should fix this. Thanks.

**Comment by whreams** [comment]
Thanks much for the quick response!!!

On Aug 14, 2020, at 4:02 PM, hjdhjd <notifications@github.com> wrote:

﻿
Please update to v2.1.10 - just published. Should fix this. Thanks.
